services:
  grafana:
    user: root
    container_name: 'tencent-cls-grafana-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-6.5.3}
        #grafana_version: ${GRAFANA_VERSION:-7.5.17}
        #grafana_version: ${GRAFANA_VERSION:-8.5.27}
        #grafana_version: ${GRAFANA_VERSION:-9.5.21}
        #grafana_version: ${GRAFANA_VERSION:-10.4.14}
        #grafana_version: ${GRAFANA_VERSION:-11.4.0}
        development: ${DEVELOPMENT:-true}
    ports:
      - 3008:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/tencent-cls-grafana-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/tencent-cls-grafana-datasource
      - ./grafana-data:/var/lib/grafana

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.tencent-cls-grafana-datasource:debug
      GF_LOG_LEVEL: debug
      #GF_LOG_CONSOLE_FORMAT: json
      #GF_LOG_FILE_FORMAT: json
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: tencent-cls-grafana-datasource
      GF_INSTALL_PLUGINS: https://github.com/grafana/piechart-panel/releases/download/v1.6.4/grafana-piechart-panel-1.6.4.zip;grafana-piechart-panel
