version: '3'

services:
  #grafana-7:
  #  image: grafana/grafana:7.4.0
  #  container_name: grafana7
  #  ports:
  #   - '3001:3000'
  #  volumes:
  #    - ./:/var/lib/grafana/plugins/tencent-cls-grafana-datasource
  #    - ./conf/grafana.ini:/etc/grafana/grafana.ini

  grafana-dev:
    image: grafana/grafana:9.4.0
    container_name: grafana
    ports:
      - '3001:3000'
    volumes:
      - ./:/var/lib/grafana/plugins/tencent-cls-grafana-datasource
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
