services:
  grafana:
    user: root
    container_name: 'tencent-cls-grafana-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-9.4.0}
        development: ${DEVELOPMENT:-true}
    ports:
      - 3001:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - "apparmor:unconfined"
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/tencent-cls-grafana-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/tencent-cls-grafana-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.tencent-cls-grafana-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: tencent-cls-grafana-datasource
