name: release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.16
      -
        name: Set up Mage
        uses: magefile/mage-action@v3
        with:
          install-only: true
      -
        name: Show Mage version
        run: mage --version
      - 
        name: Build
        run: |
          yarn
          go mod vendor
          npm run buildPkg
      
